baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Recipes'
theme = 'lightbi-hugo'

[[menu.main]]
  identifier = "recipes"
  name = "Recipes"
  url = "/recipes/"
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
