name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          curl -s -o /usr/local/bin/hugo https://github.com/gohugoio/hugo/releases/download/v0.92.0/hugo_0.92.0_Linux-64bit.tar.gz
          tar -xvf /usr/local/bin/hugo -C /usr/local/bin
          rm /usr/local/bin/hugo

      - name: Build and deploy
        run: |
          hugo
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin main